### ISSUE TITLE
xpca: unable to open response file 

### ISSUE THREAD

**Issue by xross** [xmos/xcommon_cmake#129]
Place holder issue pending more info.

On occasion get errors such as 

xpca: unable to open response file "@/Users/ross/sandboxes/sb_uac/sw_usb_audio/app_usb_aud_xk_316_mc_multirate_i2s/.build_2AMi2o2xxxxxx_asrc_96/_pca.rsp

cleaning project resolves

**Comment by danielpieczko** [comment]
Reproduced and understood:
- when cmake configures the project, it creates `.build/_pca.rsp` and then the xpca command will work when xmake runs
- if you "xmake clean", the contents of `.build` will be deleted
- if you then run xmake again, xpca will report this error as `_pca.rsp` is not present
- re-running cmake will resolve this as it will re-create `.build/_pca.rsp`

This can be fixed either by requiring a custom command to generate _pca.rsp before the xpca command runs, or by creating _pca.rsp in a location that won't be cleaned. I think I prefer the latter: put it inside the build directory as its contents are fixed at cmake configuration time.
