### ISSUE TITLE
Add static library dependencies of a static library

### ISSUE THREAD

**Issue by danielpieczko** [xmos/xcommon_cmake#67]
While building xcore-voice using cmake_xcommon, I think it would be useful to be able to have dependencies of a static library which are static libraries themselves.

I don't think it's practical to actually combine them into a single .a file: as far as I can tell, `ar` can only add object files to an existing archive. So you would have to extract the objects from one static library and insert them into another.

To do this with cmake I think we can add commands in the cmake include file generated as part of the static library build to define the relationship and then the sub-dependencies will be transitively linked into an application.

Example: build lib_foo.a which depends on lib_bar.a. The lib_foo-xs3a.cmake include file contains an include command to pull in lib_bar-xs3a.cmake, and a target_link_libraries(lib_foo-xs3a INTERFACE lib_bar-xs3a) command. Then the application will link against target lib_foo-xs3a, which causes target lib_bar-xs3a also to be linked.

**Comment by xross** [comment]
This is now done. See tests/static_lib_depend_static_static for example.

Note, this doesn't include "wrapping" one lib into another.
