### ISSUE TITLE
Report when Tools haven't been sourced

### ISSUE THREAD

**Issue by danielpieczko** [xmos/xcommon_cmake#75]
Suggestion from Huw when he tripped over this in another cmake project.

You configure cmake for your application. Then you come back to it later in a new environment and haven't sourced XTC Tools. If you just try to build the project, you get hard to diagnose errors and it's not obvious that you are only missing the tools.

It would be nicer to be able to have a check early on to ensure that your environment is correct.

**Comment by danielpieczko** [comment]
I tested this myself by running cmake with the tools present, then re-running cmake on the same build directory in a new terminal without the tools - that worked. Then if you try to run xmake it will fail saying xmake is not present. I think that this is clear enough, so closing as "won't fix".

**Comment by xross** [comment]
I think this becomes more pertinent when setting XMOS_CMAKE_PATH gets added to SetupEnv

I think this just boils down to checking XMOS_CMAKE_PATH is set and if not producing a readable error, not just an include fail.

**Comment by danielpieczko** [comment]
But I think that's a "chicken-and-egg" situation - if XMOS_CMAKE_PATH isn't set, it won't reach any code we write because that all comes from `$XMOS_CMAKE_PATH/xcommon.cmake` so we can't produce a useful error. Otherwise it's extra boiler-plate code at the top of the application like we used to have in the tests. The top-level CMakeLists.txt would end up like this:
```
cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED XMOS_CMAKE_PATH)
    message(FATAL_ERROR "XMOS_CMAKE_PATH not set)
endif()
include($ENV{XMOS_CMAKE_PATH}/xcommon.cmake)
project(app_name)
...
```
